# This file is for AWS CodeDeploy, which handles deploying the application 
# to EC2 instances or updating an ECS service.
version: 1.0
os: linux 

files:
  - source: /
    destination: /home/ec2-user/ci-cd-demo/

hooks:
  # installs Docker on the EC2 instance before starting the application
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
  # Runs the script to start the Docker container
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  # Validates that the service is running correctly after deployment
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300